"""Public observations and synthetic demonstrations for the v3 belief policy.

The encoder never calls the teacher. It receives the *whole public belief*, not
the sampled actual world. Its only summaries are one-action expectations. Text,
IDs, context, and family labels are excluded. Exact five-step contingent search
is confined to data labeling. Held-out examples are generated by the evaluator
only after freezing the training configuration/checkpoint.
"""
from dataclasses import replace
from itertools import permutations
import math
import random

import numpy as np

from agent_lab.belief import (BeliefAction, BeliefProblem, Hypothesis, Outcome,
                              STOP, NEEDS_INFORMATION, branches, plan, verified)

MAX_HYPOTHESES = 4
MAX_OUTCOMES = 2
MAX_FACTS = 12
MAX_ACTIONS = 10
MAX_CANDIDATES = 12
FEATURE_DIM = 400
SEED_DOMAINS = {"train": 310_000_000, "validation": 320_000_000, "test": 330_000_000}
FAMILIES = {
    "train": ("diagnosis", "clarification", "known_cause", "flaky_tool", "noisy_evidence"),
    "validation": ("layered_diagnosis", "costly_confirmation", "diagnose_flaky", "revised_goal"),
    "test": ("four_way_revision", "noisy_flaky_revision", "prepared_uncertainty", "revised_stochastic_goal"),
}


def _bits(mask):
    return tuple(float(bool(mask & (1 << i))) for i in range(MAX_FACTS))


def _entropy(belief):
    return -math.fsum(h.probability * math.log(h.probability) for h in belief if h.probability)


def _check(problem, depth, token_weight, latency_weight):
    if type(depth) is not int or not 1 <= depth <= 5:
        raise ValueError("Depth must be an integer between 1 and 5.")
    for value in (token_weight, latency_weight):
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or value < 0:
            raise ValueError("Cost weights must be finite nonnegative numbers.")
    if token_weight + latency_weight == 0:
        raise ValueError("At least one cost weight must be positive.")
    if len(problem.belief) > MAX_HYPOTHESES:
        raise ValueError("The v3 encoder supports at most 4 live hypotheses; no truncation is performed.")
    # Check retained mappings too: silently accepting an unsupported model is
    # surprising when a later public belief revives one of its declared worlds.
    for action in problem.actions:
        for outcomes in (action.outcomes, *action.outcomes_by_world.values()):
            if len(outcomes) > MAX_OUTCOMES:
                raise ValueError("The v3 encoder supports at most 2 outcomes per world and action.")


def _outcome_rows(action, ordered):
    """Represent observation equivalence, never the spelling of labels.

    Outcome order is immaterial. Observation classes are ordered by their full
    occurrence signature, so renaming any observation leaves features intact.
    """
    entries = []
    for wi, h in enumerate(ordered):
        entries.append(sorted(action.effects(h.world_id),
                              key=lambda o: (o.probability, o.sets, o.clears)))
    signatures = {}
    for wi, outcomes in enumerate(entries):
        for o in outcomes:
            signatures.setdefault(o.observation, []).append((wi, o.probability, o.sets, o.clears))
    # Equal signatures describe duplicate, informationally equivalent labels.
    # Assigning the same partition column preserves their separate probabilities
    # in separate outcome slots without an arbitrary dependence on label text.
    signatures = {k: tuple(sorted(v)) for k, v in signatures.items()}
    classes = {signature: i for i, signature in enumerate(sorted(set(signatures.values())))}
    encoded = []
    for wi in range(MAX_HYPOTHESES):
        outcomes = [] if wi >= len(entries) else sorted(
            entries[wi], key=lambda o: (o.probability, o.sets, o.clears, classes[signatures[o.observation]]))
        for oi in range(MAX_OUTCOMES):
            if oi >= len(outcomes):
                encoded.extend((0.0,) * 34)
            else:
                o = outcomes[oi]
                column = classes[signatures[o.observation]]
                encoded.extend((1.0, o.probability, *_bits(o.sets), *_bits(o.clears),
                                *(float(j == column) for j in range(8))))
    return tuple(encoded)


def _canonical_orders(problem):
    """Canonicalize <=4 public hypotheses without using world/action IDs.

    Tied canonical orders represent observable symmetries. A candidate takes
    its smallest representation across these orders; this also avoids an action
    array order breaking a world symmetry.
    """
    by_belief = {}
    for order in permutations(problem.belief):
        key = tuple((h.state, h.probability) for h in order)
        by_belief.setdefault(key, []).append(order)
    candidates = by_belief[min(by_belief)]
    best, winners = None, []
    for order in candidates:
        key = tuple(sorted((a.requires, a.forbids, a.allowed, a.tokens, a.latency_ms,
                            _outcome_rows(a, order)) for a in problem.actions))
        if best is None or key < best:
            best, winners = key, [order]
        elif key == best:
            winners.append(order)
    return winners


def encode_belief(problem, depth=5, token_weight=1.0, latency_weight=.01):
    """Return (features, valid slots, hard eligibility, candidate metadata).

    Shape is [12, 400]. Four padded hypotheses contain current state/probability;
    each action has two padded outcomes per hypothesis, effects/probabilities,
    and eight observation-equivalence columns. No hidden sampled world, search
    score, target action, or multistep lookahead enters these features.
    """
    if isinstance(problem, dict):
        problem = BeliefProblem.from_dict(problem)
    _check(problem, depth, token_weight, latency_weight)
    orders = _canonical_orders(problem)
    order = orders[0]
    done = verified(problem.belief, problem.goal)
    goal_count = max(1, problem.goal.bit_count())
    candidates = [{"id": a.id, "name": a.name} for a in problem.actions]
    candidates.extend([{"id": STOP, "name": "Finish: goal verified"},
                       {"id": NEEDS_INFORMATION, "name": "Request information or revise the plan"}])
    x = np.zeros((MAX_CANDIDATES, FEATURE_DIM), np.float32)
    valid = np.zeros(MAX_CANDIDATES, bool)
    eligible = np.zeros(MAX_CANDIDATES, bool)
    global_features = list(_bits(problem.goal)) + list(_bits((1 << len(problem.facts)) - 1))
    for wi in range(MAX_HYPOTHESES):
        global_features.extend((*_bits(order[wi].state), order[wi].probability, 1.0)
                               if wi < len(order) else (0.0,) * 14)
    cost_scale = max([1.] + [a.tokens * token_weight + a.latency_ms * latency_weight for a in problem.actions])
    weight_scale = max(token_weight + 100 * latency_weight, 1e-12)
    before = math.fsum(h.probability * (h.state & problem.goal).bit_count() / goal_count for h in order)
    entropy = _entropy(order)
    for i, candidate in enumerate(candidates):
        regular = i < len(problem.actions)
        stop = candidate["id"] == STOP
        action = problem.actions[i] if regular else BeliefAction(candidate["id"], candidate["name"])
        ready = action.eligible(problem.belief)
        can_run = (ready and not done) if regular else (done if stop else not done)
        effect_features = min(_outcome_rows(action, alternative) for alternative in orders)
        child_rows = branches(problem.belief, action) if regular and ready else ()
        after = math.fsum(p * math.fsum(h.probability * (h.state & problem.goal).bit_count() / goal_count
                                      for h in belief) for _, p, belief in child_rows) if child_rows else before
        immediate_success = math.fsum(p for _, p, belief in child_rows if verified(belief, problem.goal))
        information = entropy - math.fsum(p * _entropy(belief) for _, p, belief in child_rows) if child_rows else 0.
        scalar = [math.log1p(action.tokens) / math.log(10001),
                  math.log1p(action.latency_ms) / math.log(60001),
                  (action.tokens * token_weight + action.latency_ms * latency_weight) / cost_scale,
                  problem.goal.bit_count() / MAX_FACTS, len(problem.facts) / MAX_FACTS,
                  len(order) / MAX_HYPOTHESES, entropy / math.log(MAX_HYPOTHESES),
                  float(done), float(can_run), float(regular), float(stop), float(not regular and not stop),
                  float(action.allowed), depth / 5, token_weight / weight_scale,
                  100 * latency_weight / weight_scale, before, after, immediate_success,
                  information / math.log(MAX_HYPOTHESES),
                  math.fsum(h.probability * (action.requires & ~h.state).bit_count() / MAX_FACTS for h in order),
                  math.fsum(h.probability * (action.forbids & h.state).bit_count() / MAX_FACTS for h in order),
                  math.fsum(h.probability for h in order if h.state & problem.goal == problem.goal),
                  len(problem.actions) / MAX_ACTIONS]
        x[i] = global_features + list(_bits(action.requires)) + list(_bits(action.forbids)) + list(effect_features) + scalar
        valid[i], eligible[i] = True, can_run
    return x, valid, eligible, candidates


def _split_name(split):
    split = "validation" if split == "valid" else split
    if split not in FAMILIES:
        raise ValueError("Split must be train, validation, or test.")
    return split


def family_for_seed(seed, split):
    split = _split_name(split)
    return FAMILIES[split][seed % len(FAMILIES[split])]


def _remap_mask(value, permutation):
    return sum(1 << permutation[i] for i in range(len(permutation)) if value & (1 << i))


def _scramble(problem, rng):
    """Break accidental bit positions, names, world ordering and action ordering."""
    permutation = list(range(len(problem.facts)))
    rng.shuffle(permutation)
    facts = [""] * len(permutation)
    for i, fact in enumerate(problem.facts):
        facts[permutation[i]] = fact
    worlds = sorted({h.world_id for h in problem.belief} |
                    {w for a in problem.actions for w in a.outcomes_by_world})
    rng.shuffle(worlds)
    names = {w: f"hypothesis_{i}_{rng.randrange(10**8)}" for i, w in enumerate(worlds)}
    remap = lambda mask: _remap_mask(mask, permutation)
    def outcomes(rows):
        rows = [replace(o, sets=remap(o.sets), clears=remap(o.clears)) for o in rows]
        rng.shuffle(rows)
        return tuple(rows)
    actions = [replace(a, id=f"choice_{rng.randrange(10**12):012d}", requires=remap(a.requires),
                       forbids=remap(a.forbids), outcomes=outcomes(a.outcomes),
                       outcomes_by_world={names[w]: outcomes(rows) for w, rows in a.outcomes_by_world.items()})
               for a in problem.actions]
    rng.shuffle(actions)
    belief = [replace(h, world_id=names[h.world_id], state=remap(h.state)) for h in problem.belief]
    rng.shuffle(belief)
    return replace(problem, facts=tuple(facts), goal=remap(problem.goal), belief=tuple(belief), actions=tuple(actions))


def make_problem(seed, split="train"):
    """Construct a seeded declared-world software decision with no actual world.

    Train and validation have different compositions; final test compositions
    are reserved and must only be instantiated after the candidate is frozen.
    Data generation never samples a persistent hidden state.
    """
    split = _split_name(split)
    family = family_for_seed(seed, split)
    rng = random.Random(seed)
    n = 1 if family in ("known_cause", "flaky_tool", "revised_stochastic_goal") else (
        4 if family == "four_way_revision" else 3 if family == "layered_diagnosis" else 2)
    worlds = [f"cause_{i}" for i in range(n)]
    masses = [rng.uniform(.15, 1.) for _ in worlds]
    masses = [m / sum(masses) for m in masses]
    fixed, tested, blocked, prepared, docs, evidence = [1 << i for i in range(6)]
    facts = ("repair_applied", "acceptance_verified", "repair_blocked", "workspace_ready", "documentation_verified", "evidence_obtained")
    preparation = family in ("layered_diagnosis", "prepared_uncertainty")
    noisy = family in ("noisy_evidence", "noisy_flaky_revision")
    flaky = family in ("flaky_tool", "diagnose_flaky", "noisy_flaky_revision", "revised_stochastic_goal")
    revision = family in ("revised_goal", "four_way_revision", "noisy_flaky_revision", "revised_stochastic_goal")
    state = 0 if preparation else prepared
    belief = tuple(Hypothesis(w, state, p) for w, p in zip(worlds, masses))
    actions = []
    if preparation:
        actions.append(BeliefAction("prepare", "Prepare the isolated workspace", forbids=prepared,
                                   outcomes=(Outcome(1., "ready", sets=prepared),), tokens=rng.randint(1, 12), latency_ms=rng.randint(1, 40)))
    inspect_cost = rng.randint(2, 30)
    inspect = BeliefAction("inspect", "Ask for the requirement" if family == "clarification" else "Inspect the uncertain cause",
                          requires=prepared, tokens=inspect_cost, latency_ms=rng.randint(1, 200),
                          outcomes_by_world={w: (Outcome(1., f"observed_{i}", sets=evidence),) for i, w in enumerate(worlds)})
    actions.append(inspect)
    if noisy:
        accuracy = rng.choice([.6, .75, .9])
        actions.append(BeliefAction("noisy_check", "Read an unreliable diagnostic", requires=prepared,
                                   tokens=max(1., inspect_cost / 5), latency_ms=1.,
                                   outcomes_by_world={w: (Outcome(accuracy, f"signal_{i}", sets=evidence),
                                                           Outcome(1 - accuracy, f"signal_{1-i}", sets=evidence))
                                                      for i, w in enumerate(worlds)}))
    for i, w in enumerate(worlds):
        repair_outcomes = {}
        for possible in worlds:
            if possible == w:
                repair_outcomes[possible] = (Outcome(1., "patch_applied", sets=fixed),)
            else:
                repair_outcomes[possible] = (Outcome(1., "repair_failed", sets=blocked, clears=fixed | tested),)
        actions.append(BeliefAction(f"repair_{i}", f"Apply the repair for cause {i + 1}",
                                   requires=prepared, forbids=blocked | fixed, outcomes_by_world=repair_outcomes,
                                   tokens=rng.randint(2, 30), latency_ms=rng.randint(1, 100)))
    success = rng.choice([.45, .65, .8, .95]) if flaky else 1.
    verification = (Outcome(success, "checks_passed", sets=tested),)
    if success < 1:
        verification += (Outcome(1 - success, "checks_failed"),)
    actions.append(BeliefAction("verify", "Run the acceptance checks", requires=fixed,
                               forbids=blocked | tested, outcomes=verification,
                               tokens=rng.randint(1, 15), latency_ms=rng.randint(10, 150)))
    # More expensive comprehensive repair is often avoidable but can be the
    # winning route at a short horizon or if diagnosis costs more than repair.
    actions.append(BeliefAction("comprehensive", "Apply and verify a comprehensive repair", requires=prepared,
                               forbids=blocked, outcomes=(Outcome(1., "all_passed", sets=fixed | tested),),
                               tokens=rng.randint(40, 160), latency_ms=rng.randint(80, 700),
                               allowed=rng.random() > .3))
    actions.append(BeliefAction("docs", "Update the requested documentation", requires=prepared,
                               outcomes=(Outcome(1., "docs_passed", sets=docs),), tokens=rng.randint(1, 20), latency_ms=rng.randint(1, 70)))
    actions.append(BeliefAction("repeat", "Repeat a redundant status check", tokens=rng.randint(0, 4), latency_ms=rng.randint(1, 10)))
    goal = tested
    if revision:
        # A new requested win replaces the old objective while retaining facts.
        # Sometimes the original repair has already been applied.
        if rng.random() < .5:
            belief = tuple(replace(h, state=h.state | fixed) for h in belief)
        goal = rng.choice([docs, docs | tested])
    if family == "costly_confirmation":
        belief = (replace(belief[rng.randrange(n)], probability=1.),)
    # Some starts are already finished; stopping is explicitly a hard rule.
    if rng.random() < .06:
        belief = tuple(replace(h, state=h.state | goal) for h in belief)
    # No recoverable repair remains. The label means unavailable within the
    # declared model/horizon, not that a real-world goal is impossible.
    elif rng.random() < .05:
        belief = tuple(replace(h, state=h.state | blocked) for h in belief)
    problem = BeliefProblem(f"belief_{split}_{seed}", facts, goal, belief, tuple(actions),
                            f"Synthetic {family}; achieve only the currently declared acceptance goal.")
    return _scramble(problem, rng)


def target_ids(solution):
    """Preserve exact objective ties instead of rewarding arbitrary action IDs."""
    chosen = solution["chosen_action_id"]
    if chosen in (STOP, NEEDS_INFORMATION):
        return [chosen]
    fields = ("expected_verified_success", "expected_cost", "expected_steps")
    return [row["action_id"] for row in solution["action_scores"]
            if row.get("eligible") and not row.get("pruned") and all(
                math.isclose(row[field], solution[field], abs_tol=1e-12, rel_tol=0) for field in fields)]


def generate_rows(count, split, seed):
    """Generate exact-search labels and reachable Bayesian posterior states.

    A posterior prefix follows a sampled observable branch of a teacher plan;
    no hidden world is retained or exposed. The prefix is recorded for audit.
    Incomplete node-budget search is rejected, never used as a target.
    """
    split = _split_name(split)
    if type(count) is not int or count < 1:
        raise ValueError("Count must be a positive integer.")
    rows, xx, vv, ee, yy = [], [], [], [], []
    for i in range(count):
        case_seed = seed + i
        rng = random.Random(case_seed ^ 0x5371)
        problem = make_problem(case_seed, split)
        token_weight = rng.choice([.25, 1., 2., 4.])
        latency_weight = rng.choice([.001, .01, .05, .2])
        depth = rng.randint(1, 5) if i % 5 == 0 else 5
        history = []
        goal_revision = None
        if i % 9 == 0:
            # Current goals, never old goals, enter the observation. Revisions
            # are present in training; reserved families compose them with new
            # uncertainty/transition structures at final evaluation.
            docs = 1 << problem.facts.index("documentation_verified")
            new_goal = docs if rng.random() < .5 else docs | problem.goal
            goal_revision = {"previous_goal": problem.goal, "current_goal": new_goal}
            problem = replace(problem, goal=new_goal)
        if i % 4 == 1 and depth > 1 and not verified(problem.belief, problem.goal):
            available = [a for a in problem.actions if a.eligible(problem.belief)]
            stochastic = [a for a in available if any(len(a.effects(h.world_id)) > 1 for h in problem.belief)]
            if available:
                # Exploratory observations expose misleading noisy diagnostics
                # and repair failures that an optimal root plan might avoid.
                action = rng.choice(stochastic or available)
                observable = branches(problem.belief, action)
                label, _, posterior = rng.choices(observable, weights=[b[1] for b in observable])[0]
                problem = replace(problem, belief=posterior)
                history.append({"action_id": action.id, "observation": label,
                                "source": "exploratory_public_observation"})
                depth -= 1
        solution = plan(problem, depth, token_weight, latency_weight, max_nodes=100_000)
        if not solution["search_complete"]:
            raise RuntimeError(f"Incomplete teacher search for {case_seed}; label discarded.")
        # Half of training examples and a deterministic validation subset cover
        # re-observation and shrinking horizons after acting, rather than roots
        # alone. Histories contain only public observations and prior actions.
        if i % 2 == 0:
            for _ in range(rng.randrange(min(depth, 4))):
                node = solution["plan"]
                if node["kind"] != "action" or depth <= 1:
                    break
                branch = rng.choices(node["branches"], weights=[b["probability"] for b in node["branches"]])[0]
                problem = replace(problem, belief=tuple(Hypothesis(**h) for h in branch["posterior"]))
                history.append({"action_id": node["action_id"], "observation": branch["observation"],
                                "source": "teacher_plan_public_observation"})
                depth -= 1
                solution = plan(problem, depth, token_weight, latency_weight, max_nodes=100_000)
                if not solution["search_complete"]:
                    raise RuntimeError(f"Incomplete posterior teacher search for {case_seed}; label discarded.")
        x, valid, eligible, candidates = encode_belief(problem, depth, token_weight, latency_weight)
        winners = target_ids(solution)
        target = np.array([float(c["id"] in winners) for c in candidates] + [0.] * (MAX_CANDIDATES - len(candidates)), np.float32)
        if not target.sum() or not eligible[target > 0].all():
            raise RuntimeError("Teacher target is absent or violates a hard rule.")
        target /= target.sum()
        rows.append({"problem": problem.to_dict(), "family": family_for_seed(case_seed, split),
                     "split": split, "seed": case_seed, "source": "synthetic_declared_world_exact_contingent_search",
                     "token_weight": token_weight, "latency_weight": latency_weight,
                     "max_depth": depth, "target_ids": winners, "public_history": history,
                     "goal_revision": goal_revision,
                     "teacher": {k: solution[k] for k in ("search_complete", "expected_verified_success", "expected_cost", "expected_steps", "explored_nodes")}})
        xx.append(x); vv.append(valid); ee.append(eligible); yy.append(target)
        if (i + 1) % 2000 == 0:
            print(f"Generated belief {split}: {i + 1}/{count}", flush=True)
    return rows, (np.stack(xx), np.stack(vv), np.stack(ee), np.stack(yy))
